Collection.Web/Controllers/CollectionController.cs
using Collection.Business.Services;
using Collection.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Collection.Data.Models;

namespace Collection.Web.Controllers
{
    public class CollectionController : Controller
    {
        private readonly CollectionDbContext dbContext;
        private readonly ICollectionTypeService collectionTypeService;
        private readonly ICollectionService collectionService;
        private int userId;
        public CollectionController()
        {
            this.dbContext = new CollectionDbContext();
            this.collectionService = new CollectionService(this.dbContext);
            this.collectionTypeService = new CollectionTypeService(this.dbContext);
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string collectionId, string colDate)
        {
            userId = int.Parse(User.Identity.GetUserId());
            await collectionService.Delete(int.Parse(collectionId));
            await dbContext.SaveChangesAsync();
            return await GetCollections(DateTime.Parse(colDate));
        }

        [HttpPost]
        public async Task<ActionResult> DeleteType(int id)
        {
            await collectionTypeService.Delete(id);
            await dbContext.SaveChangesAsync();
            return  _CollectionTypes();
        }

        // GET: Collection
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> GetCollections(DateTime colDate)
        {
            userId = int.Parse(User.Identity.GetUserId());
            var model = await collectionService.GetAllByDateAsync(userId, colDate);
            return PartialView("_Collections",model);
        }

        [HttpPost]
        public async Task<ActionResult> AddType(string collectionType,bool selType)
        {
            userId = int.Parse(User.Identity.GetUserId());

            CollectionType type = new CollectionType();
            type.UserId = userId;
            type.Sales = selType;
            type.Type = collectionType;

            collectionTypeService.Create(type);
            dbContext.SaveChanges();
            var model = collectionTypeService.GetDefaultType();
            model.AddRange(await collectionTypeService.GetAllByUserIDAsync(userId));
            return PartialView("_CollectionTypes", model); ;
        }
        [HttpPost]
        public async Task<ActionResult> AddCollection(string collectionType,string amount, string colDate)
        {
            userId = int.Parse(User.Identity.GetUserId());

            Data.Models.Collection collection = new Data.Models.Collection();
            collection.UserId = userId;
            collection.CollectionType = await collectionTypeService.GetAllByTypeID(int.Parse(collectionType));
            collection.CollectionDate = DateTime.Parse(colDate);
            collection.Amount =Decimal.Parse(amount);

            collectionService.Create(collection);
            dbContext.SaveChanges();

            var model = await collectionService.GetAllByDateAsync(userId, collection.CollectionDate);
            return PartialView("_Collections", model); ;
        }

        public ActionResult _CollectionTypes()
        {
            userId = int.Parse(User.Identity.GetUserId());
            var model =  collectionTypeService.GetDefaultType();
            model.AddRange(collectionTypeService.GetAllByUserID(userId));
            //var model = collectionTypeService.GetAllByUserID(userId);
            return PartialView("_CollectionTypes", model); ;
        }

        [Authorize]
        public ActionResult Report()
        {
            return View();
        }
        [HttpPost]
        public ActionResult GetCollectionsReport(int year, int month,string reportType)
        {
            userId = int.Parse(User.Identity.GetUserId());
            List<Data.Models.Collection> collections = collectionService.GetByMonthAndYear(userId, year,month);
            switch (reportType)
            {
                case "sales":
                    collections = collections.Where(x => x.CollectionType.Sales == true).ToList();
                    break;
                case "expense":
                    collections = collections.Where(x => x.CollectionType.Sales == false).ToList();
                    break;
                case "revenue":
                    List<Data.Models.Collection> collectionSales = collections.Where(x => x.CollectionType.Sales == true).ToList();
                    List<Data.Models.Collection> collectionExpense = collections.Where(x => x.CollectionType.Sales == false).ToList();
                    collections = new List<Data.Models.Collection>();

                    int day = DateTime.DaysInMonth(year, month);
                    for (int i = 1; i <= day; i++)
                    {
                        decimal sales = collectionSales.Where(b => b.CollectionDate.Day == i).Sum(x=>x.Amount);
                        decimal expense = collectionExpense.Where(b => b.CollectionDate.Day == i).Sum(x => x.Amount);
                        //if (sales != null)
                        //{
                        //    salesAmount = sales.Amount;
                        //}
                        //if (expense != null) { 
                        //    expenseAmount = expense.Amount;
                        //}
                        decimal revenueAmount = sales - expense;
                        collections.Add(new Data.Models.Collection { Amount = sales, CollectionDate = new DateTime(collectionSales.FirstOrDefault().CollectionDate.Year, collectionSales.FirstOrDefault().CollectionDate.Month,i), CollectionType = new CollectionType { Type="Sales" } });
                        collections.Add(new Data.Models.Collection { Amount = expense, CollectionDate = new DateTime(collectionSales.FirstOrDefault().CollectionDate.Year, collectionSales.FirstOrDefault().CollectionDate.Month, i), CollectionType = new CollectionType { Type = "Expense" } });
                        collections.Add(new Data.Models.Collection { Amount = revenueAmount, CollectionDate = new DateTime(collectionSales.FirstOrDefault().CollectionDate.Year, collectionSales.FirstOrDefault().CollectionDate.Month, i), CollectionType = new CollectionType { Type = "Revenue" } });
                    }
                    break;
            }
            if (reportType.Equals("monthend"))
            {
                //var allCollectionsSales = collections.Where(x=>x.CollectionType.Sales == true).Select(x => new CollectionModel { Type = x.CollectionType.Type, Amount = x.Amount, Day = x.CollectionDate.Day }).OrderBy(x => x.Day).GroupBy(h => h.Type).ToList();
                var allCollectionsSales = collections.Where(x => x.CollectionType.Sales == true).GroupBy(x=>x.CollectionTypeId,(key,y)=>y.Select(x => new CollectionModel { Type = x.CollectionType.Type, Amount = y.Sum(z=>z.Amount), Day = x.CollectionDate.Day }).OrderBy(x => x.Day)).ToList();
                var allCollectionsExpense = collections.Where(x => x.CollectionType.Sales == false).GroupBy(x => x.CollectionTypeId, (key, y) => y.Select(x => new CollectionModel { Type = x.CollectionType.Type, Amount = y.Sum(z => z.Amount), Day = x.CollectionDate.Day }).OrderBy(x => x.Day)).ToList();
                Dictionary<string, List<CollectionModel>> collectionTotalByTypes = new Dictionary<string, List<CollectionModel>>();
                List<CollectionModel> collectionSales = new List<CollectionModel>();
                foreach (var sales in allCollectionsSales)
                {
                    collectionSales.Add(sales.First());
                }
                collectionTotalByTypes.Add("sales", collectionSales);
                List<CollectionModel> collectionExpense = new List<CollectionModel>();
                foreach (var expense in allCollectionsExpense)
                {
                    collectionExpense.Add(expense.First());
                }
                collectionTotalByTypes.Add("Expense", collectionExpense);
                return Json(collectionTotalByTypes.ToList());
            }
            else
            {
                var allCollectionsByType = collections.Select(x => new CollectionModel { Type = x.CollectionType.Type, Amount = x.Amount, Day = x.CollectionDate.Day }).OrderBy(x => x.Day).GroupBy(h => h.Type).ToList();
                Dictionary<string, List<decimal>> collectionTotalByTypes = new Dictionary<string, List<decimal>>();

                int days = DateTime.DaysInMonth(year, month);

                foreach (var item in allCollectionsByType)
                {
                    List<CollectionModel> items = item.ToList();
                    List<decimal> collectionPerDay = new List<decimal>();
                    for (int i = 1; i <= days; i++)
                    {
                        decimal coll = items.Where(b => b.Day == i).Sum(x => x.Amount);
                        collectionPerDay.Add(coll);
                    }
                    collectionTotalByTypes.Add(items[0].Type, collectionPerDay);
                }
                return Json(collectionTotalByTypes.ToList());
            }
        }
    }
    public class CollectionModel
    {
        public string Type { get; set; }
        public decimal Amount { get; set; }
        public int Day { get; set; }
        public bool IsSale { get; set; }
    }
}

Collection.Web/Views/Collection/Report.cshtml
@{
    ViewBag.Title = "Report";
}
<div class="col-xs-12 form-inline">
    <select class="form-control" name="monthpicker" id="monthpicker">
        <option value="1">January</option>
        <option value="2">February</option>
        <option value="3">March</option>
        <option value="4">April</option>
        <option value="5">May</option>
        <option value="6">June</option>
        <option value="7">July</option>
        <option value="8">August</option>
        <option value="9">September</option>
        <option value="10">October</option>
        <option value="11">November</option>
        <option value="12">December</option>
    </select>
    <select class="form-control" name="yearpicker" id="yearpicker"></select>
    <button class="btn btn-success" id="btnGetReport">Generate</button>
    <button class="btn btn-primary" id="btnPrint" style="display:none;" >Print</button>
</div>
<div class="col-xs-12" id="radio" style="display:none;">
    <label class="radio-inline">
    <input type="radio" name="optradio" value="sales" id="btnDetails">Sales Details
    </label>
    <label class="radio-inline">
        <input type="radio" value="expense" name="optradio" id="btnAll">Expense Details
    </label>
    <label class="radio-inline">
        <input type="radio" value="revenue" name="optradio" id="btnRevenue">Revenue Details
    </label>
    <label class="radio-inline">
        <input type="radio" value="monthend" name="optradio" id="btnMonthEnd">Month End
    </label>
</div> 
<div class="col-xs-12">
    <div id="container" style="min-width: 310px; height: 400px; margin: 15px auto"></div>
</div> 
<div class="col-xs-12 table-responsive" id="report-table">

</div>

<script>



    Highcharts.wrap(Highcharts.Chart.prototype, 'initReflow', function (proceed) {
        var chart = this;

        proceed.call(this);

        if (window.matchMedia) {
            window.matchMedia('print').addListener(function reflow() {
                chart.reflow();
            });
        }
    });

    $(document).ready(function () {
        $("#breadcrumb").html('');
        $("#breadcrumb").append("<li><a href='@Url.Action("Index","Home")'>Home</a></li>");
        $("#breadcrumb").append("<li><a href='@Url.Action("Index","Collection")'>Collection</a></li>");
        for (i = new Date().getFullYear() ; i > 1990; i--) {
            $('#yearpicker').append($('<option />').val(i).html(i));
        }

        $("#btnPrint").on("click", function () {
            window.print();
        })

        $("#btnGetReport").on("click", function () {
            var a = $("input[name='optradio']:checked").val()
            if (a == undefined) {
                $("#btnDetails").click();
            }
            var reportType = $("input[name='optradio']:checked").val()
            var selMonth = $("#monthpicker").val();
            var selYear = $("#yearpicker").val();
            var month = $("#monthpicker option:selected").text();
            $.ajax({
                url: "@Url.Action("GetCollectionsReport", "Collection")",
                data: { year: selYear, month: selMonth, reportType: reportType },
                type: "POST",
                success: function (data) {
                    $("#report-table").html("");
                    $("#container").html("");
                    $("#btnPrint").hide();
                    $("#radio").hide();
                    if (reportType == "monthend") {
                        $("#radio").show();
                        $("#btnPrint").show();
                        $("#container").hide();
                        var sales = data[0].Value;
                        var expense = data[1].Value;
                        var allSales = 0.00;
                        var allExpense = 0.00;
                        var html = "<table class='table table-bordered' style='width:500px;margin:0 auto;'><tr><td colspan='2' style=' color:blue;'>Total Sales</td></tr>"
                        for (var i = 0; i < sales.length; i++) {
                            html += "<tr><td>" + sales[i].Type + "</td><td align='right'>" + FormatNumberToDecimal(sales[i].Amount) + "</td></tr>"
                            allSales += sales[i].Amount;
                        }
                        html += "<tr><td align='right' style='color:blue;'>Total</td><td align='right';>" + FormatNumberToDecimal(allSales) + "</td></tr>";
                        html += "<tr><td colspan='2' style='color:red;'>Total Expense</td></tr>";
                        for (var i = 0; i < expense.length; i++) {
                            html += "<tr><td>" + expense[i].Type + "</td><td align='right'>" + FormatNumberToDecimal(expense[i].Amount) + "</td></tr>"
                            allExpense += expense[i].Amount;
                        }
                        html += "<tr><td align='right' style='color:red;'>Total</td><td align='right'>" + FormatNumberToDecimal(allExpense) + "</td></tr>";
                        var income = Number(allSales) - Number(allExpense);
                        html += "<tr><td style='color:green;'>Total Income</td><td align='right'>" + FormatNumberToDecimal(income) + "</td></tr>";
                        $("#report-table").append(html);
                    }
                    else {
                        if (data.length > 0) {
                            $("#radio").show();
                            $("#btnPrint").show();
                            $("#container").show();
                            var dayColumn = [];
                            var dayInMonth = moment(selYear + "-" + selMonth, "YYYY-MM").daysInMonth();
                            for (var i = 1; i <= dayInMonth; i++) {
                                dayColumn.push("Day " + i);
                            }
                            var seriesData = [];

                            $.each(data, function (i, val) {
                                if (true) {

                                }
                                var seriesEntry = { name: '', data: null };
                                seriesEntry.name = val.Key;
                                seriesEntry.data = val.Value;
                                seriesData.push(seriesEntry);
                            });

                            var reportDetails = [];
                            var header = false;
                            var seriesTotal = [];
                            for (var b = 0; b <= dayInMonth; b++) {

                                var reportData = Object();
                                if (!header) {
                                    reportData["Day"] = "Date";
                                    $.each(data, function (i, val) {
                                        reportData["Value" + i] = val.Key;
                                    });
                                    reportData["Total"] = "Total";
                                    reportDetails.push(reportData);
                                    header = true;
                                }
                                else {

                                    var total = 0;
                                    reportData["Day"] = month + " " + b;
                                    $.each(data, function (i, val) {
                                        total += Number(val.Value[b - 1]);
                                        reportData["Value" + i] = val.Value[b - 1];
                                    });
                                    if (reportType !== "revenue") {
                                        reportData["Total"] = total;
                                    }
                                    seriesTotal.push(total);
                                    reportDetails.push(reportData);
                                }
                            }
                            var seriesAll = [];
                            var seriesEntry = { name: '', data: null };
                            seriesEntry.name = "Total";
                            seriesEntry.data = seriesTotal;
                            seriesAll.push(seriesEntry);
                            var html = "<table class='table table-bordered'><thead><tr><th class='text-center'>" + reportDetails[0].Day + "</th>";

                            $.each(data, function (i, val) {
                                html += "<th class='text-right'>" + reportDetails[0]["Value" + i] + "</th>";
                            });
                            if (reportType !== "revenue") {
                                html += "<th class='text-right'>" + reportDetails[0]["Total"] + "</th>";
                            }
                            html += "</tr></thead><tbody>";
                            for (var c = 1; c <= dayInMonth; c++) {
                                html += "<tr> <td class='text-center'>" + reportDetails[c]["Day"] + "</td>  ";

                                $.each(data, function (i, val) {
                                    html += "<td class='text-right'>" + FormatNumberToDecimal(reportDetails[c]["Value" + i]) + "</td>";
                                });
                                if (reportType !== "revenue") {
                                    html += "<td class='text-right'>" + FormatNumberToDecimal(reportDetails[c]["Total"]) + "</td>  ";
                                }
                                html += "</tr>";
                            }
                            $("#report-table").append(html);

                            var chart = Highcharts.chart('container', {
                                chart: {
                                    type: 'column'
                                },
                                title: {
                                    text: 'Daily Collection for the Month of ' + month + " " + selYear
                                },

                                xAxis: {
                                    categories: dayColumn,
                                    crosshair: true
                                },

                                yAxis: {
                                    min: 0,
                                    title: {
                                        text: 'Amount (php)'
                                    }
                                },
                                tooltip: {
                                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                                        '<td style="padding:0"><b>{point.y:.2f}</b></td></tr>',
                                    footerFormat: '</table>',
                                    shared: true,
                                    useHTML: true
                                },
                                plotOptions: {
                                    column: {
                                        pointPadding: 0.2,
                                        borderWidth: 0
                                    }
                                },
                                series: seriesData
                            });
                            $('#btnDetails').on("click", function () {
                                $("#btnGetReport").click()
                            });
                            $('#btnAll').on("click", function () {
                                $("#btnGetReport").click()
                            });
                            $('#btnRevenue').on("click", function () {
                                $("#btnGetReport").click()
                            });
                            $('#btnMonthEnd').on("click", function () {
                                $("#btnGetReport").click()
                            });
                        }
                    }
                }
            });
        });
    });


</script>

Collection.Web/Views/Collection/_CollectionTypes.cshtml
@model IEnumerable<Collection.Data.Models.CollectionType>
@using Microsoft.AspNet.Identity
<div id="modal-types" class="modal fade" tabindex="-8" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4>Select Collection Type</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12" style="height:200px;overflow-y:auto;">
                        <table class="table table-hover" id="select-type">
                            <thead>
                                <tr>
                                    <th colspan="2">Type</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        if (item.Sales == true)
                                        {
                                            <tr>
                                                <td class="type" data-id="@item.CollectionTypeId">@item.Type</td>
                                                
                                                @if (item.CollectionTypeId != 44)
                                                {
                                                    <td class="delete" data-id="@item.CollectionTypeId"><i class="fa fa-trash fa-lg red" aria-hidden="true"></i></td>
                                                }

                                            </tr>
                                        }

                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    @if (User.Identity.GetUserName().AsBool())
                    {
                        <div class="col-xs-12">
                            <button type="button" id="btnAddTypeExpense" class="btn btn-primary">Add Type</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div id="modal-expense" class="modal fade" tabindex="-8" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4>Select Collection Type</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-12" style="height:200px;overflow-y:auto;">
                        <table class="table table-hover" id="select-type">
                            <thead>
                                <tr>
                                    <th colspan="2">Type</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null)
                                {
                                    foreach (var item in Model)
                                    {
                                        if (item.Sales == false)
                                        {
                                            <tr>
                                                <td class="type" data-id="@item.CollectionTypeId">@item.Type</td>
                                               @if (item.CollectionTypeId != 45)
                                               {
                                                <td class="delete" data-id="@item.CollectionTypeId"><i class="fa fa-trash fa-lg red" aria-hidden="true"></i></td>
                                               }
                                            </tr>
                                        }

                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    @if (User.Identity.GetUserName().AsBool())
                    {
                        <div class="col-xs-12">
                            <button type="button" id="btnAddType" class="btn btn-primary">Add Type</button>
                        </div>
                    }
                       
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>
<div id="modal-add-type" class="modal fade" role="dialog" tabindex="-5">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">&times;</span></button>
                <h4>Enter Collection Type</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Type:</label>
                    <input type="text" class="form-control" id="collectionType" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnCancelType" class="btn btn-danger">Cancel</button>
                <button type="submit" id="btnSaveType" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>
<div id="modal-add-expense-type" class="modal fade" role="dialog" tabindex="-5">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="close"><span aria-hidden="true">&times;</span></button>
                <h4>Enter Collection Type</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Type:</label>
                    <input type="text" class="form-control" id="collectionExpenseType" />
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="btnCancelExpenseType" class="btn btn-danger">Cancel</button>
                <button type="submit" id="btnSaveExpenseType" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

Collection.Web/Views/Collection/_Collections.cshtml
@model IEnumerable<Collection.Data.Models.Collection>
<div class="col-sm-6">
    <p>Sales</p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Type</th>
                <th colspan="2">Amount</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    if (item.CollectionType.Sales == true)
                    {
                        <tr>
                            <td>@(item.CollectionType == null ? String.Empty : @item.CollectionType.Type)</td>
                            <td>@String.Format("{0:n2}", @item.Amount)</td>

                            <td>
                                <button title="Delete Collection" data-id="@item.CollectionId" class="btn-delete"><i class="fa fa-trash fa-lg red" aria-hidden="true"></i></button>
                            </td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>
<div class="col-sm-6">
    <p>Expense</p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Type</th>
                <th colspan="2">Amount</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                    if (item.CollectionType.Sales == false)
                    {
                        <tr>
                            <td>@(item.CollectionType == null ? String.Empty : @item.CollectionType.Type)</td>
                            <td>@String.Format("{0:n2}", @item.Amount)</td>

                            <td>
                                <button title="Delete Collection" data-id="@item.CollectionId" class="btn-delete"><i class="fa fa-trash fa-lg red" aria-hidden="true"></i></button>
                            </td>
                        </tr>
                    }

                }
            }
        </tbody>
    </table>
</div>
<script>
    $(document).ready(function () {
        $("#breadcrumb").html('');
        $("#breadcrumb").append("<li><a href='@Url.Action("Index","Home")'>Home</a></li>");
        $(".btn-delete").on("click", function () {
            var deleteId = $(this).attr("data-id");
            var colDate = $("#colDate").val();
            $.ajax({
                url: "@Url.Action("Delete","Collection")",
                type: "POST",
                data: { "collectionId": deleteId, "colDate": colDate },
                success: function (data) {
                    $(".table-responsive").html(data);
                }
            });
        });
    });
</script>